INSERT INTO CARS (CAR_ID, MANUFACTURER, MODEL, REGISTRATION_NUMBER, FUEL_TYPE, CATEGORY, COLOR, TOTAL_SEATS) VALUES
(1, 'TOYOTA', 'CAMRY', 'KA03JJ0675', 'PETROL', 'SEDAN', 'WHITE', 4),
(2, 'TOYOTA', 'CAMRY', 'KA03JJ0778', 'DIESEL', 'SEDAN', 'BLACK', 5),
(3, 'BMW', '650', 'KA03JJ0123', 'PETROL', 'SEDAN', 'RED', 4),
(4, 'BMW', '650', 'KA03JJ0456', 'DIESEL', 'SEDAN', 'BLUE', 5);